version: "3.8"

services:

  accounts:
    image: hendersonporfirio/microservice-account
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - tuyosistema-network

  loans:
    image: hendersonporfirio/microservice-loans
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - tuyosistema-network

  cards:
    image: hendersonporfirio/microservice-cards
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - tuyosistema-network

networks:
  tuyosistema-network: