version: "3.8"

services:

  accounts:
    image: hendersonporfirio/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - tuyosistema-network

  loans:
    image: tuyosistema/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - tuyosistema-network

  cards:
    image: tuyosistema/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - tuyosistema-network

networks:
  tuyosistema-network: